services:
  - type: web
    name: story-weaver-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: GOOGLE_API_KEY
        sync: false
      - key: UNSPLASH_ACCESS_KEY
        sync: false 